version: "1"
rules: # Array of rules
  - base: main # Required. Target branch
    upstream: SkyCryptWebsite:main # Required. Must be in the same fork network.
  - base: dev
    upstream: SkyCryptWebsite:dev # Required. Can be a branch in the same forked repo.
label: ":arrow_heading_down: pull" # Optional
conflictLabel: "merge-conflict" # Optional, on merge conflict assign a custom label, Default: merge-conflict
